# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\AutoScriptForGF\modules\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1005, 700)
        Form.setStyleSheet("QWidget\n"
"{\n"
"background-color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton,QTextBrowser,QStackedWidget,QLineEdit\n"
"{\n"
"    border-style: solid;\n"
"    border: 2px solid silver;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border-style: solid;\n"
"    border: 2px solid silver;\n"
"    border-radius: 5px;\n"
"    background-color: gainsboro;\n"
"}\n"
"QCheckBox:hover\n"
"{\n"
"    background-color: gainsboro;\n"
"}\n"
"QWight\n"
"{\n"
"    background-color: white;\n"
"}\n"
"QRadioButton\n"
"{\n"
"    border-style: solid;\n"
"    border: 2px solid silver;\n"
"    border-radius: 5px;\n"
"}\n"
"QComboBox\n"
"{\n"
"    border-style: solid;\n"
"    border: 2px solid silver;\n"
"    border-radius: 5px;\n"
"}\n"
"QComboBox:drop-down {\n"
"subcontrol-origin: padding;\n"
"\n"
"subcontrol-position: top right;\n"
"\n"
"width: 30px;\n"
"\n"
"border-left-width: 0px;\n"
"\n"
"border-left-color: gray;\n"
"\n"
"border-left-style: solid;\n"
"\n"
"border-top-right-radius: 3px;\n"
"\n"
"border-bottom-right-radius: 3px;\n"
"\n"
"}")
        self.Page = QtWidgets.QStackedWidget(Form)
        self.Page.setGeometry(QtCore.QRect(30, 80, 961, 601))
        self.Page.setToolTip("")
        self.Page.setStatusTip("")
        self.Page.setWhatsThis("")
        self.Page.setStyleSheet("QStackedWidget#Page\n"
"{\n"
"    border-style: solid;\n"
"    border: 2px solid silver;\n"
"    border-radius: 5px;\n"
"}")
        self.Page.setObjectName("Page")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_1)
        self.stackedWidget_2.setGeometry(QtCore.QRect(20, 20, 180, 370))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.checkBox_6 = QtWidgets.QCheckBox(self.page)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 185, 160, 35))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox = QtWidgets.QCheckBox(self.page)
        self.checkBox.setGeometry(QtCore.QRect(10, 10, 160, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setWhatsThis("")
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_3 = QtWidgets.QCheckBox(self.page)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 80, 160, 35))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.page)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 115, 160, 35))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 45, 160, 35))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_8 = QtWidgets.QCheckBox(self.page)
        self.checkBox_8.setGeometry(QtCore.QRect(10, 220, 160, 35))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.page)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 255, 160, 35))
        self.checkBox_9.setObjectName("checkBox_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.page)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 325, 80, 35))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.page)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 325, 80, 35))
        self.pushButton_5.setObjectName("pushButton_5")
        self.checkBox_10 = QtWidgets.QCheckBox(self.page)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 290, 160, 35))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_5 = QtWidgets.QCheckBox(self.page)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 150, 160, 35))
        self.checkBox_5.setObjectName("checkBox_5")
        self.stackedWidget_2.addWidget(self.page)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget_2.addWidget(self.page_5)
        self.checkBox_7 = QtWidgets.QCheckBox(self.page_1)
        self.checkBox_7.setGeometry(QtCore.QRect(230, 40, 141, 31))
        self.checkBox_7.setObjectName("checkBox_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_1)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 470, 151, 35))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_1)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 530, 151, 35))
        self.pushButton_7.setObjectName("pushButton_7")
        self.comboBox = QtWidgets.QComboBox(self.page_1)
        self.comboBox.setGeometry(QtCore.QRect(60, 423, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(self.page_1)
        self.label_6.setGeometry(QtCore.QRect(10, 425, 51, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_1)
        self.label_7.setGeometry(QtCore.QRect(230, 80, 61, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.page_1)
        self.lineEdit.setGeometry(QtCore.QRect(300, 80, 131, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.running_text = QtWidgets.QTextBrowser(self.page_1)
        self.running_text.setGeometry(QtCore.QRect(450, 20, 490, 560))
        self.running_text.setStyleSheet("QTextBrowser#running_text\n"
"{\n"
"    border-style: solid;\n"
"    border: 2px solid silver;\n"
"    border-radius: 5px;\n"
"}")
        self.running_text.setObjectName("running_text")
        self.checkBox_11 = QtWidgets.QCheckBox(self.page_1)
        self.checkBox_11.setGeometry(QtCore.QRect(230, 115, 91, 19))
        self.checkBox_11.setObjectName("checkBox_11")
        self.Page.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setGeometry(QtCore.QRect(40, 90, 101, 16))
        self.label_11.setObjectName("label_11")
        self.comboBox_4 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_4.setGeometry(QtCore.QRect(140, 90, 131, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_5.setGeometry(QtCore.QRect(140, 40, 131, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setGeometry(QtCore.QRect(40, 40, 101, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(40, 140, 101, 16))
        self.label_13.setObjectName("label_13")
        self.comboBox_2 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_2.setGeometry(QtCore.QRect(40, 170, 131, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_3.setGeometry(QtCore.QRect(170, 170, 87, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser.setGeometry(QtCore.QRect(40, 290, 221, 211))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 200, 76, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(40, 240, 72, 15))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 235, 50, 21))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_9.setGeometry(QtCore.QRect(130, 200, 76, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.Page.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.page_3)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(210, 30, 721, 451))
        self.stackedWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_adb = QtWidgets.QWidget()
        self.page_adb.setObjectName("page_adb")
        self.label = QtWidgets.QLabel(self.page_adb)
        self.label.setGeometry(QtCore.QRect(15, 20, 161, 21))
        self.label.setObjectName("label")
        self.Button_select_adb = QtWidgets.QPushButton(self.page_adb)
        self.Button_select_adb.setGeometry(QtCore.QRect(650, 15, 51, 31))
        self.Button_select_adb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_select_adb.setObjectName("Button_select_adb")
        self.text_adb = QtWidgets.QLineEdit(self.page_adb)
        self.text_adb.setGeometry(QtCore.QRect(160, 15, 475, 31))
        self.text_adb.setObjectName("text_adb")
        self.label_4 = QtWidgets.QLabel(self.page_adb)
        self.label_4.setGeometry(QtCore.QRect(60, 80, 72, 15))
        self.label_4.setObjectName("label_4")
        self.text_address = QtWidgets.QLineEdit(self.page_adb)
        self.text_address.setGeometry(QtCore.QRect(160, 70, 475, 31))
        self.text_address.setObjectName("text_address")
        self.label_5 = QtWidgets.QLabel(self.page_adb)
        self.label_5.setGeometry(QtCore.QRect(160, 120, 431, 16))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page_adb)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_3 = QtWidgets.QLabel(self.page_4)
        self.label_3.setGeometry(QtCore.QRect(70, 40, 72, 15))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_4)
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        self.pushButton.setGeometry(QtCore.QRect(30, 35, 149, 35))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.Page.addWidget(self.page_3)
        self.page_debug = QtWidgets.QWidget()
        self.page_debug.setObjectName("page_debug")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_debug)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 30, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_debug)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 90, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.Page.addWidget(self.page_debug)
        self.Button_1 = QtWidgets.QPushButton(Form)
        self.Button_1.setGeometry(QtCore.QRect(0, 0, 335, 50))
        self.Button_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_1.setStyleSheet("QPushButton#Button_1\n"
"{\n"
"color:rgb(50, 108, 243);\n"
"border: 2px solid rgb(50, 108, 243);\n"
"border-radius: 0px;\n"
"border-style: hidden hidden solid hidden;\n"
"}\n"
"QPushButton#Button_1:hover\n"
"{\n"
"background-color: #FFFFFF ;\n"
"border-style: hidden hidden solid hidden;\n"
"}\n"
"QPushButton#Button_1:checked\n"
"{\n"
"border: 2px solid rgb(50, 108, 243);\n"
"border-radius: 0px;\n"
"border-style: hidden hidden solid hidden;\n"
"}")
        self.Button_1.setObjectName("Button_1")
        self.Button_2 = QtWidgets.QPushButton(Form)
        self.Button_2.setGeometry(QtCore.QRect(335, 0, 335, 50))
        self.Button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_2.setStyleSheet("QPushButton#Button_2\n"
"{\n"
"border: 2px solid silver;\n"
"border-radius: 0px;\n"
"border-style: hidden hidden solid hidden;\n"
"}\n"
"QPushButton#Button_2:hover\n"
"{\n"
"background-color: #FFFFFF ;\n"
"border-style: hidden hidden solid hidden;\n"
"}\n"
"")
        self.Button_2.setObjectName("Button_2")
        self.Button_3 = QtWidgets.QPushButton(Form)
        self.Button_3.setGeometry(QtCore.QRect(670, 0, 335, 50))
        self.Button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_3.setStyleSheet("QPushButton#Button_3\n"
"{\n"
"border: 2px solid silver;\n"
"border-radius: 0px;\n"
"border-style: hidden hidden solid hidden;\n"
"}\n"
"QPushButton#Button_3:hover\n"
"{\n"
"background-color: #FFFFFF ;\n"
"border-style: hidden hidden solid hidden;\n"
"}\n"
"")
        self.Button_3.setObjectName("Button_3")
        self.Button_1.raise_()
        self.Button_2.raise_()
        self.Button_3.raise_()
        self.Page.raise_()

        self.retranslateUi(Form)
        self.Page.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_6.setText(_translate("Form", "每日六战"))
        self.checkBox.setText(_translate("Form", "自动登录"))
        self.checkBox_3.setText(_translate("Form", "人形制造"))
        self.checkBox_4.setText(_translate("Form", "装备制造"))
        self.checkBox_2.setText(_translate("Form", "自动后勤"))
        self.checkBox_8.setText(_translate("Form", "动能模拟"))
        self.checkBox_9.setText(_translate("Form", "势能模拟"))
        self.pushButton_4.setText(_translate("Form", "全选"))
        self.pushButton_5.setText(_translate("Form", "反选"))
        self.checkBox_10.setText(_translate("Form", "访问好友"))
        self.checkBox_5.setText(_translate("Form", "装备强化"))
        self.checkBox_7.setText(_translate("Form", "六战后持续运行"))
        self.pushButton_6.setText(_translate("Form", "连接模拟器"))
        self.pushButton_7.setText(_translate("Form", "停止"))
        self.comboBox.setItemText(0, _translate("Form", "无动作"))
        self.comboBox.setItemText(1, _translate("Form", "退出少女前线"))
        self.comboBox.setItemText(2, _translate("Form", "退出AS"))
        self.comboBox.setItemText(3, _translate("Form", "关闭模拟器"))
        self.comboBox.setItemText(4, _translate("Form", "退出并关闭模拟器"))
        self.comboBox.setItemText(5, _translate("Form", "休眠*"))
        self.comboBox.setItemText(6, _translate("Form", "关机*"))
        self.label_6.setText(_translate("Form", "完成后"))
        self.label_7.setText(_translate("Form", "指定次数"))
        self.running_text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.checkBox_11.setText(_translate("Form", "跳过强化"))
        self.label_11.setText(_translate("Form", "装备制造选择"))
        self.comboBox_4.setItemText(0, _translate("Form", "光学瞄具"))
        self.comboBox_4.setItemText(1, _translate("Form", "全息瞄具"))
        self.comboBox_4.setItemText(2, _translate("Form", "红点瞄具"))
        self.comboBox_4.setItemText(3, _translate("Form", "夜战装备"))
        self.comboBox_4.setItemText(4, _translate("Form", "消音器"))
        self.comboBox_4.setItemText(5, _translate("Form", "穿甲弹"))
        self.comboBox_4.setItemText(6, _translate("Form", "状态弹"))
        self.comboBox_4.setItemText(7, _translate("Form", "高速弹"))
        self.comboBox_4.setItemText(8, _translate("Form", "霰弹"))
        self.comboBox_4.setItemText(9, _translate("Form", "外骨骼"))
        self.comboBox_4.setItemText(10, _translate("Form", "防弹插板"))
        self.comboBox_4.setItemText(11, _translate("Form", "弹链箱"))
        self.comboBox_4.setItemText(12, _translate("Form", "伪装披风"))
        self.comboBox_4.setItemText(13, _translate("Form", "备用瞄具"))
        self.comboBox_4.setItemText(14, _translate("Form", "芯片"))
        self.comboBox_4.setItemText(15, _translate("Form", "特殊穿甲弹"))
        self.comboBox_5.setItemText(0, _translate("Form", "手枪"))
        self.comboBox_5.setItemText(1, _translate("Form", "冲锋枪"))
        self.comboBox_5.setItemText(2, _translate("Form", "步枪"))
        self.comboBox_5.setItemText(3, _translate("Form", "突击步枪"))
        self.comboBox_5.setItemText(4, _translate("Form", "机枪"))
        self.comboBox_5.setItemText(5, _translate("Form", "4442"))
        self.label_12.setText(_translate("Form", "人形制造选择"))
        self.label_13.setText(_translate("Form", "动能模拟选择"))
        self.comboBox_2.setItemText(0, _translate("Form", "强化演习"))
        self.comboBox_2.setItemText(1, _translate("Form", "资料采样"))
        self.comboBox_2.setItemText(2, _translate("Form", "经验特训"))
        self.comboBox_2.setItemText(3, _translate("Form", "经验特训-特种"))
        self.comboBox_2.setItemText(4, _translate("Form", "云图回廊"))
        self.comboBox_2.setItemText(5, _translate("Form", "防御演习"))
        self.comboBox_3.setItemText(0, _translate("Form", "高级训练"))
        self.comboBox_3.setItemText(1, _translate("Form", "中级训练"))
        self.comboBox_3.setItemText(2, _translate("Form", "初级训练"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:26pt;\"><br /></p></body></html>"))
        self.pushButton_8.setText(_translate("Form", "添加"))
        self.label_2.setText(_translate("Form", "剩余动能:"))
        self.pushButton_9.setText(_translate("Form", "清除最新"))
        self.label.setText(_translate("Form", "adb路径(相对/绝对)"))
        self.Button_select_adb.setText(_translate("Form", "选择"))
        self.label_4.setText(_translate("Form", "连接地址:"))
        self.label_5.setText(_translate("Form", "请填写IP+端口  例如：127.0.0.1:62001"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "连接设置"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.pushButton_3.setText(_translate("Form", "PushButton"))
        self.Button_1.setText(_translate("Form", "一键长草"))
        self.Button_2.setText(_translate("Form", "任务配置"))
        self.Button_3.setText(_translate("Form", "设置"))
